# Generated by Django 2.1.2 on 2018-10-13 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('account', '0001_initial'),
        ('course', '0002_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('name', models.CharField(max_length=50, verbose_name='Quiz Name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Percentage')),
                ('course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.Course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='account.User')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Quiz Grade')),
                ('completion', models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Completion')),
                ('finished_in', models.DateTimeField()),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.User')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
            options={
                'verbose_name': 'Quiz Participant',
                'verbose_name_plural': 'Quiz Participants',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='participants',
            field=models.ManyToManyField(related_name='participants', through='quiz.QuizParticipant', to='account.User'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, to='question.Question'),
        ),
    ]
