# Generated by Django 2.1.2 on 2018-10-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('multichoice', 'Multichoice'), ('truefalse', 'True-False')], default='multichoice', max_length=50, verbose_name='Question Type')),
                ('answer', models.CharField(blank=True, max_length=255, verbose_name='Answer')),
            ],
        ),
    ]
